In [158]:
import torch.tensor as Tensor
import torch as torch
from torch.autograd import Variable

In [159]:
x_data = [1.0, 2.0, 3.0]
y_data = [2.0, 4.0, 6.0]

In [160]:
w = Variable(torch.Tensor([1.0]), requires_grad = True) # Any random value
w

tensor([1.], requires_grad=True)

In [167]:
x = Variable(torch.randn(1,10))

prev_h = Variable(torch.randn(1,20), requires_grad = True)

W_h = Variable(torch.randn(20,20), requires_grad = True)

W_x = Variable(torch.randn(20,10), requires_grad = True)

In [173]:
i2h = torch.mm(W_x, x.t())

h2h = torch.mm(W_h, prev_h.t())

next_h = i2h + h2h

next_h = next_h.tanh()

In [174]:
next_h.backward(torch.ones(1,20).t()) # dnext_h / dW_x

In [175]:
print(W_x.grad)

tensor([[-2.9795e-03, -1.8440e-03,  1.0237e-03, -7.1981e-03, -3.2329e-03,
         -3.4554e-04,  2.6289e-03,  6.5204e-04, -1.9075e-03, -2.7961e-03],
        [-1.4740e-05, -9.1224e-06,  5.0644e-06, -3.5609e-05, -1.5993e-05,
         -1.7094e-06,  1.3005e-05,  3.2257e-06, -9.4366e-06, -1.3833e-05],
        [-2.1327e-02, -1.3199e-02,  7.3279e-03, -5.1524e-02, -2.3141e-02,
         -2.4734e-03,  1.8817e-02,  4.6673e-03, -1.3654e-02, -2.0015e-02],
        [-8.7736e-01, -5.4300e-01,  3.0146e-01, -2.1196e+00, -9.5198e-01,
         -1.0175e-01,  7.7412e-01,  1.9200e-01, -5.6171e-01, -8.2337e-01],
        [-7.9892e-04, -4.9445e-04,  2.7450e-04, -1.9301e-03, -8.6686e-04,
         -9.2654e-05,  7.0490e-04,  1.7484e-04, -5.1148e-04, -7.4975e-04],
        [-7.7577e-07, -4.8013e-07,  2.6655e-07, -1.8742e-06, -8.4175e-07,
         -8.9970e-08,  6.8448e-07,  1.6977e-07, -4.9666e-07, -7.2803e-07],
        [-3.2284e-01, -1.9981e-01,  1.1093e-01, -7.7994e-01, -3.5030e-01,
         -3.7441e-02,  2.8485e-0

In [176]:
# Our model forward pass

def forward(x):
    return x * w

In [177]:
# Loss function

def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y)**2

In [178]:
print("predict (before training)", 4, forward(4).data[0])

predict (before training) 4 tensor(4.)


In [179]:
# Training loop

for epoch in range(6):
    for x_val, y_val in zip(x_data, y_data):
        l = loss(x_val, y_val)
        l.backward()
        print("\tgrad: ", x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data
        
        # Manually zero the gradients after updating weights
        w.grad.data.zero_()
        
    print("progress:", epoch, l.data[0])
    
# After training

print("predict (after training)", 4, forward(4).data[0])

	grad:  1.0 2.0 tensor(-2.)
	grad:  2.0 4.0 tensor(-7.8400)
	grad:  3.0 6.0 tensor(-16.2288)
progress: 0 tensor(7.3159)
	grad:  1.0 2.0 tensor(-1.4786)
	grad:  2.0 4.0 tensor(-5.7962)
	grad:  3.0 6.0 tensor(-11.9981)
progress: 1 tensor(3.9988)
	grad:  1.0 2.0 tensor(-1.0932)
	grad:  2.0 4.0 tensor(-4.2852)
	grad:  3.0 6.0 tensor(-8.8704)
progress: 2 tensor(2.1857)
	grad:  1.0 2.0 tensor(-0.8082)
	grad:  2.0 4.0 tensor(-3.1681)
	grad:  3.0 6.0 tensor(-6.5580)
progress: 3 tensor(1.1946)
	grad:  1.0 2.0 tensor(-0.5975)
	grad:  2.0 4.0 tensor(-2.3422)
	grad:  3.0 6.0 tensor(-4.8484)
progress: 4 tensor(0.6530)
	grad:  1.0 2.0 tensor(-0.4417)
	grad:  2.0 4.0 tensor(-1.7316)
	grad:  3.0 6.0 tensor(-3.5845)
progress: 5 tensor(0.3569)
predict (after training) 4 tensor(7.3468)


In [180]:
l = loss(x = 1, y = 2)

### Other part

In [149]:
x = torch.randn(3, requires_grad = True)
x

tensor([-0.1377, -1.5363,  2.2986], requires_grad=True)

In [150]:
y = x + 2
y

tensor([1.8623, 0.4637, 4.2986], grad_fn=<AddBackward0>)

In [153]:
z = y * y * 2
z

tensor([ 6.9361,  0.4300, 36.9566], grad_fn=<MulBackward0>)

In [155]:
z = z.mean()
z

tensor(14.7742, grad_fn=<MeanBackward0>)

In [156]:
z.backward()